version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 20533b11-fcfb-41f6-b484-8fc367349ac9
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
