version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 5f0b2e04-ad01-441b-8e3b-c84e4acf2931
  endpoints: public
  env:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
