version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: fake-version-does-not-exist
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
