version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 5772ba23-7597-4163-a9e2-158203dd17b7
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
