version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 08e59b9f-804b-48b2-821f-b356433e3882
  endpoints: public
  env:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
