version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 07fe695a-bd82-44f9-a6a9-f45c9371706f
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
