version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: d62374ce-f7e6-4428-9bce-6eca5d62fd46
  endpoints: public
  env:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
