version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 0a541b6c-b6c5-478e-9d9d-94b67f36546f
  endpoints: public
  env:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
