version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 42043e9b-87bb-4aa1-bf32-da7c5b576727
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
