version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 10f08b5f-3f1b-4629-a3c5-8e88be7f4c9b
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
