version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: f1e8d373-f787-4fd2-bf23-cefa399e92bc
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
