version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 10b5145c-a05c-43e6-9822-5a4f35396bc3
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
