version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 975ec646-9125-498a-9ed3-ca510e31f500
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
